### PR TITLE
OscOS interpolation: crossfade within oversampling window; faster formula

### PR DESCRIPTION
**Pull request by jamshark70**
1. buf_loc interpolation will be smoother if we hold buf_loc steady within the oversampling window, and crossfade from one to the next. Optimization if buf_loc didn't change. This will sound better for rapid buf_loc modulation.

2. Linear interpolation formula:
   - `a * (1-xf) + b * xf` = 2 multiplies, 2 add/sub
   - `(b-a) * xf + a` = 1 multiply, 2 add/sub = faster

### CODE REVIEW

**Comment by jamshark70** [comment]
If the strategy is zero-order-hold within the oversampling window, a further optimization would be to move the Process() calls out of the loop:

```
  float OscOS::next_os(const float* table0, float phase, float buf_divs, float buf_loc, int table_size, float fmaxindex)
  {
    float out, y0a, y0b;
    
    float phase1 = sc_clip(phase, 0.f, 1.0f);
    float buf_loc1 = sc_clip(buf_loc, 0.f, 1.0f);

    int osRatio = oversample.getOversamplingRatio();
    if(buf_loc1 == m_last_buf_loc) {
      y0a = Perform(table0, phase1, buf_divs, buf_loc1, table_size, fmaxindex);
      for (int k = 0; k < osRatio; k++){
        osBuffer[k] = y0a;
      }
    } else {
      float y0a = Perform(table0, phase1, buf_divs, m_last_buf_loc, table_size, fmaxindex);
      float y0b = Perform(table0, phase1, buf_divs, buf_loc1, table_size, fmaxindex);
      for (int k = 0; k < osRatio; k++) {
        osBuffer[k] = (y0b - y0a) * ((float) k / osRatio) + y0a;
      }
    }

    m_last_buf_loc = buf_loc1;

    if (m_oversamplingIndex != 0)
      out = oversample.downsample();
    else
      out = osBuffer[0];
    return out;
  }
```

BTW the rationale for my suggestion is: One of the problems I had with my MultiWtOsc pseudo-UGen is that rapid modulation of the equivalent of `buf_loc` would produce clicks. Eventually I realized that this was because the crossfade between wavetable positions wasn't actually crossfading, if the input was changing too quickly, e.g.:

- sample 0 = buf_loc 63.71
- sample 1 = buf_loc 53.71
- sample 2 = buf_loc 43.71
- sample 3 = buf_loc 33.71

Between these adjacent samples, the "fading out" signal is changing every sample = discontinuity = click.

Mulling this over yesterday, I realized that it would be valid to use the oversampling window to perform the cross fade:

- sample 0 = buf_loc 63.71
- sample 1 = buf_loc 53.71
  - 1a = 100% 63.71, 0% 53.71
  - 1b = 75% 63.71, 25% 53.71
  - 1c = 50% 63.71, 50% 53.71
  - 1d = 25% 63.71, 75% 53.71
- sample 2 = buf_loc 43.71
  - 2a = 100% 53.71, 0% 43.71
  - 2b = 75% 53.71, 25% 43.71
  - 2c = 50% 53.71, 50% 43.71
  - 2d = 25% 53.71, 75% 43.71

That's a very short transition, but it is an actual transition, and the downsampling filter should take care of the rest.

I tested both OscOS and my MultiWtOsc with the same series of formant wave tables, and found that mine is significantly more "zippery" than OscOS with these alterations.

**Comment by spluta** [comment]
Can you try out what I just uploaded? I made these changes:

1) just use classic upsampling to change the buf_loc

2) fixed the issue with upsampling the ramp input for the index. basically had to do an inverse blep, where instead of rounding off the edge of a saw wave I am correctly extending the ramp to 1 or zero, then wrapping it.

**Comment by jamshark70** [comment]
The "rapid modulation" helpfile example, with only 2 wavetables, isn't sufficient to reproduce the problem I mentioned. You'd need to scan extremely rapidly over dozens of tables. Very fast buf_loc envelopes would reveal this problem in real-world production (this is commonly done in Serum).

Here's my test:

```
(
var numTables = 20;
var size = 2048;
w = Signal(size * numTables);
numTables.do { |i|
	var amps = Array.fill(240, { |j|
		max(j absdif: i, 1/8).squared.reciprocal
	});
	w.addAll(Signal.sineFill(size, amps))
};

b.free;
b = Buffer.sendCollection(s, w, 1, -1, { "done".postln });
)

(
a = {
	(OscOS.ar(
		b,
		Phasor.ar(0, MouseY.kr(50, 200, 1) * SampleDur.ir, 0, 1),
		b.numFrames / 2048,
		MouseX.kr(0, 0.999, 0, 0.02),
		4
	) * 0.1).dup
}.play;
)
```

If you sweep the mouse left and right rapidly, you can hear a bit of roughness. (The wavetables are designed to reveal the problem; in practice, maybe it wouldn't be audible.) IMO:

- ddwWavetableSynth quark: Obvious zipper noise, not usable.
- My alterations to OscOS: A *little* roughness.
- Your alterations: Sound about the same as mine, maybe *slightly* less rough though it's very subjective.

So I wouldn't mind just closing this PR, then.

**Comment by spluta** [comment]
Cool. If you get rid of the lag you have on the MouseX that solves a lot of it. 

Also, I don't actually think what I am hearing is zipper noise. I think it is a very short envelope over a low sine wave:
`
(
    a = {
        var tri = SinOsc.ar(10).range(0,1);
        var sig = (OscOS.ar(
            b,
            LFSaw.ar(40).range(0,1),
            b.numFrames / 2048,
            tri,
            4
        ) * 0.2);
        sig.dup
    }.play
)

{SinOsc.ar(40)*(SinOsc.ar(10).clip(0.9,1)-0.9*5)}.play
`

**Comment by jamshark70** [comment]
> If you get rid of the lag you have on the MouseX that solves a lot of it.

Really? Not here. It's much worse without the lag.

**Comment by spluta** [comment]
I see. The default lag of 0.2 sounds better than the 0.02 in your code.

Sam

From: H. James Harkins ***@***.***>
Date: Sunday, January 21, 2024 at 5:48 PM
To: spluta/OversamplingOscillators ***@***.***>
Cc: spluta ***@***.***>, State change ***@***.***>
Subject: Re: [spluta/OversamplingOscillators] OscOS interpolation: crossfade within oversampling window; faster formula (PR #1)

If you get rid of the lag you have on the MouseX that solves a lot of it.

Really? Not here. It's much worse without the lag.

**Pull request closed without merging**
